'use strict';

const ABILITIES = {
  'noability': 'No Ability',
  'adaptability': 'Adaptability',
  'aftermath': 'Aftermath',
  'aerilate': 'Aerilate',
  'airlock': 'Air Lock',
  'analytic': 'Analytic',
  'angerpoint': 'Anger Point',
  'anticipation': 'Anticipation',
  'arenatrap': 'Arena Trap',
  'aromaveil': 'Aroma Veil',
  'aurabreak': 'Aura Break',
  'baddreams': 'Bad Dreams',
  'battery': 'Battery',
  'battlearmor': 'Battle Armor',
  'battlebond': 'Battle Bond',
  'beastboost': 'Beast Boost',
  'berserk': 'Berserk',
  'bigpecks': 'Big Pecks',
  'blaze': 'Blaze',
  'bulletproof': 'Bulletproof',
  'cheekpouch': 'Cheek Pouch',
  'chlorophyll': 'Chlorophyll',
  'clearbody': 'Clear Body',
  'cloudnine': 'Cloud Nine',
  'colorchange': 'Color Change',
  'comatose': 'Comatose',
  'competitive': 'Competitive',
  'compoundeyes': 'Compound Eyes',
  'contrary': 'Contrary',
  'corrosion': 'Corrosion',
  'cursedbody': 'Cursed Body',
  'cutecharm': 'Cute Charm',
  'damp': 'Damp',
  'dancer': 'Dancer',
  'darkaura': 'Dark Aura',
  'dazzling': 'Dazzling',
  'defeatist': 'Defeatist',
  'defiant': 'Defiant',
  'deltastream': 'Delta Stream',
  'desolateland': 'Desolate Land',
  'disguise': 'Disguise',
  'download': 'Download',
  'drizzle': 'Drizzle',
  'drought': 'Drought',
  'dryskin': 'Dry Skin',
  'earlybird': 'Early Bird',
  'effectspore': 'Effect Spore',
  'electricsurge': 'Electric Surge',
  'emergencyexit': 'Emergency Exit',
  'fairyaura': 'Fairy Aura',
  'filter': 'Filter',
  'flamebody': 'Flame Body',
  'flareboost': 'Flare Boost',
  'flashfire': 'Flash Fire',
  'flowergift': 'Flower Gift',
  'flowerveil': 'Flower Veil',
  'fluffy': 'Fluffy',
  'forecast': 'Forecast',
  'forewarn': 'Forewarn',
  'friendguard': 'Friend Guard',
  'frisk': 'Frisk',
  'fullmetalbody': 'Full Metal Body',
  'furcoat': 'Fur Coat',
  'galewings': 'Gale Wings',
  'galvanize': 'Galvanize',
  'gluttony': 'Gluttony',
  'gooey': 'Gooey',
  'grasspelt': 'Grass Pelt',
  'grassysurge': 'Grassy Surge',
  'guts': 'Guts',
  'harvest': 'Harvest',
  'healer': 'Healer',
  'heatproof': 'Heatproof',
  'heavymetal': 'Heavy Metal',
  'honeygather': 'Honey Gather',
  'hugepower': 'Huge Power',
  'hustle': 'Hustle',
  'hydration': 'Hydration',
  'hypercutter': 'Hyper Cutter',
  'icebody': 'Ice Body',
  'illuminate': 'Illuminate',
  'illusion': 'Illusion',
  'immunity': 'Immunity',
  'imposter': 'Imposter',
  'infiltrator': 'Infiltrator',
  'innardsout': 'Innards Out',
  'innerfocus': 'Inner Focus',
  'insomnia': 'Insomnia',
  'intimidate': 'Intimidate',
  'ironbarbs': 'Iron Barbs',
  'ironfist': 'Iron Fist',
  'justified': 'Justified',
  'keeneye': 'Keen Eye',
  'klutz': 'Klutz',
  'leafguard': 'Leaf Guard',
  'levitate': 'Levitate',
  'lightmetal': 'Light Metal',
  'lightningrod': 'Lightning Rod',
  'limber': 'Limber',
  'liquidooze': 'Liquid Ooze',
  'liquidvoice': 'Liquid Voice',
  'longreach': 'Long Reach',
  'magicbounce': 'Magic Bounce',
  'magicguard': 'Magic Guard',
  'magician': 'Magician',
  'magmaarmor': 'Magma Armor',
  'magnetpull': 'Magnet Pull',
  'marvelscale': 'Marvel Scale',
  'megalauncher': 'Mega Launcher',
  'merciless': 'Merciless',
  'minus': 'Minus',
  'mistysurge': 'Misty Surge',
  'moldbreaker': 'Mold Breaker',
  'moody': 'Moody',
  'motordrive': 'Motor Drive',
  'moxie': 'Moxie',
  'multiscale': 'Multiscale',
  'multitype': 'Multitype',
  'mummy': 'Mummy',
  'naturalcure': 'Natural Cure',
  'neuroforce': 'Neuroforce',
  'noguard': 'No Guard',
  'normalize': 'Normalize',
  'oblivious': 'Oblivious',
  'overcoat': 'Overcoat',
  'overgrow': 'Overgrow',
  'owntempo': 'Own Tempo',
  'parentalbond': 'Parental Bond',
  'pickup': 'Pickup',
  'pickpocket': 'Pickpocket',
  'pixilate': 'Pixilate',
  'plus': 'Plus',
  'poisonheal': 'Poison Heal',
  'poisonpoint': 'Poison Point',
  'poisontouch': 'Poison Touch',
  'powerconstruct': 'Power Construct',
  'powerofalchemy': 'Power of Alchemy',
  'prankster': 'Prankster',
  'pressure': 'Pressure',
  'primordialsea': 'Primordial Sea',
  'prismarmor': 'Prism Armor',
  'protean': 'Protean',
  'psychicsurge': 'Psychic Surge',
  'purepower': 'Pure Power',
  'queenlymajesty': 'Queenly Majesty',
  'quickfeet': 'Quick Feet',
  'raindish': 'Rain Dish',
  'rattled': 'Rattled',
  'receiver': 'Receiver',
  'reckless': 'Reckless',
  'refrigerate': 'Refrigerate',
  'regenerator': 'Regenerator',
  'rivalry': 'Rivalry',
  'rkssystem': 'RKS System',
  'rockhead': 'Rock Head',
  'roughskin': 'Rough Skin',
  'runaway': 'Run Away',
  'sandforce': 'Sand Force',
  'sandrush': 'Sand Rush',
  'sandstream': 'Sand Stream',
  'sandveil': 'Sand Veil',
  'sapsipper': 'Sap Sipper',
  'schooling': 'Schooling',
  'scrappy': 'Scrappy',
  'serenegrace': 'Serene Grace',
  'shadowshield': 'Shadow Shield',
  'shadowtag': 'Shadow Tag',
  'shedskin': 'Shed Skin',
  'sheerforce': 'Sheer Force',
  'shellarmor': 'Shell Armor',
  'shielddust': 'Shield Dust',
  'shieldsdown': 'Shields Down',
  'simple': 'Simple',
  'skilllink': 'Skill Link',
  'slowstart': 'Slow Start',
  'slushrush': 'Slush Rush',
  'sniper': 'Sniper',
  'snowcloak': 'Snow Cloak',
  'snowwarning': 'Snow Warning',
  'solarpower': 'Solar Power',
  'solidrock': 'Solid Rock',
  'soulheart': 'Soul-Heart',
  'soundproof': 'Soundproof',
  'speedboost': 'Speed Boost',
  'stakeout': 'Stakeout',
  'stall': 'Stall',
  'stamina': 'Stamina',
  'stancechange': 'Stance Change',
  'static': 'Static',
  'steadfast': 'Steadfast',
  'steelworker': 'Steelworker',
  'stench': 'Stench',
  'stickyhold': 'Sticky Hold',
  'stormdrain': 'Storm Drain',
  'strongjaw': 'Strong Jaw',
  'sturdy': 'Sturdy',
  'suctioncups': 'Suction Cups',
  'superluck': 'Super Luck',
  'surgesurfer': 'Surge Surfer',
  'swarm': 'Swarm',
  'sweetveil': 'Sweet Veil',
  'swiftswim': 'Swift Swim',
  'symbiosis': 'Symbiosis',
  'synchronize': 'Synchronize',
  'tangledfeet': 'Tangled Feet',
  'tanglinghair': 'Tangling Hair',
  'technician': 'Technician',
  'telepathy': 'Telepathy',
  'teravolt': 'Teravolt',
  'thickfat': 'Thick Fat',
  'tintedlens': 'Tinted Lens',
  'torrent': 'Torrent',
  'toxicboost': 'Toxic Boost',
  'toughclaws': 'Tough Claws',
  'trace': 'Trace',
  'triage': 'Triage',
  'truant': 'Truant',
  'turboblaze': 'Turboblaze',
  'unaware': 'Unaware',
  'unburden': 'Unburden',
  'unnerve': 'Unnerve',
  'victorystar': 'Victory Star',
  'vitalspirit': 'Vital Spirit',
  'voltabsorb': 'Volt Absorb',
  'waterabsorb': 'Water Absorb',
  'waterbubble': 'Water Bubble',
  'watercompaction': 'Water Compaction',
  'waterveil': 'Water Veil',
  'weakarmor': 'Weak Armor',
  'whitesmoke': 'White Smoke',
  'wimpout': 'Wimp Out',
  'wonderguard': 'Wonder Guard',
  'wonderskin': 'Wonder Skin',
  'zenmode': 'Zen Mode',
  'mountaineer': 'Mountaineer',
  'rebound': 'Rebound',
  'persistent': 'Persistent'
};

const ITEMS = {
  'abomasite': 'Abomasite',
  'absolite': 'Absolite',
  'absorbbulb': 'Absorb Bulb',
  'adamantorb': 'Adamant Orb',
  'adrenalineorb': 'Adrenaline Orb',
  'aerodactylite': 'Aerodactylite',
  'aggronite': 'Aggronite',
  'aguavberry': 'Aguav Berry',
  'airballoon': 'Air Balloon',
  'alakazite': 'Alakazite',
  'aloraichiumz': 'Aloraichium Z',
  'altarianite': 'Altarianite',
  'ampharosite': 'Ampharosite',
  'apicotberry': 'Apicot Berry',
  'armorfossil': 'Armor Fossil',
  'aspearberry': 'Aspear Berry',
  'assaultvest': 'Assault Vest',
  'audinite': 'Audinite',
  'babiriberry': 'Babiri Berry',
  'banettite': 'Banettite',
  'beastball': 'Beast Ball',
  'beedrillite': 'Beedrillite',
  'belueberry': 'Belue Berry',
  'berryjuice': 'Berry Juice',
  'bigroot': 'Big Root',
  'bindingband': 'Binding Band',
  'blackbelt': 'Black Belt',
  'blacksludge': 'Black Sludge',
  'blackglasses': 'Black Glasses',
  'blastoisinite': 'Blastoisinite',
  'blazikenite': 'Blazikenite',
  'blueorb': 'Blue Orb',
  'blukberry': 'Bluk Berry',
  'brightpowder': 'Bright Powder',
  'buggem': 'Bug Gem',
  'bugmemory': 'Bug Memory',
  'buginiumz': 'Buginium Z',
  'burndrive': 'Burn Drive',
  'cameruptite': 'Cameruptite',
  'cellbattery': 'Cell Battery',
  'charcoal': 'Charcoal',
  'charizarditex': 'Charizardite X',
  'charizarditey': 'Charizardite Y',
  'chartiberry': 'Charti Berry',
  'cheriberry': 'Cheri Berry',
  'cherishball': 'Cherish Ball',
  'chestoberry': 'Chesto Berry',
  'chilanberry': 'Chilan Berry',
  'chilldrive': 'Chill Drive',
  'choiceband': 'Choice Band',
  'choicescarf': 'Choice Scarf',
  'choicespecs': 'Choice Specs',
  'chopleberry': 'Chople Berry',
  'clawfossil': 'Claw Fossil',
  'cobaberry': 'Coba Berry',
  'colburberry': 'Colbur Berry',
  'cornnberry': 'Cornn Berry',
  'coverfossil': 'Cover Fossil',
  'custapberry': 'Custap Berry',
  'damprock': 'Damp Rock',
  'darkgem': 'Dark Gem',
  'darkmemory': 'Dark Memory',
  'darkiniumz': 'Darkinium Z',
  'dawnstone': 'Dawn Stone',
  'decidiumz': 'Decidium Z',
  'deepseascale': 'Deep Sea Scale',
  'deepseatooth': 'Deep Sea Tooth',
  'destinyknot': 'Destiny Knot',
  'diancite': 'Diancite',
  'diveball': 'Dive Ball',
  'domefossil': 'Dome Fossil',
  'dousedrive': 'Douse Drive',
  'dracoplate': 'Draco Plate',
  'dragonfang': 'Dragon Fang',
  'dragongem': 'Dragon Gem',
  'dragonmemory': 'Dragon Memory',
  'dragonscale': 'Dragon Scale',
  'dragoniumz': 'Dragonium Z',
  'dreadplate': 'Dread Plate',
  'dreamball': 'Dream Ball',
  'dubiousdisc': 'Dubious Disc',
  'durinberry': 'Durin Berry',
  'duskball': 'Dusk Ball',
  'duskstone': 'Dusk Stone',
  'earthplate': 'Earth Plate',
  'eeviumz': 'Eevium Z',
  'ejectbutton': 'Eject Button',
  'electirizer': 'Electirizer',
  'electricgem': 'Electric Gem',
  'electricmemory': 'Electric Memory',
  'electricseed': 'Electric Seed',
  'electriumz': 'Electrium Z',
  'energypowder': 'Energy Powder',
  'enigmaberry': 'Enigma Berry',
  'eviolite': 'Eviolite',
  'expertbelt': 'Expert Belt',
  'fairiumz': 'Fairium Z',
  'fairygem': 'Fairy Gem',
  'fairymemory': 'Fairy Memory',
  'fastball': 'Fast Ball',
  'fightinggem': 'Fighting Gem',
  'fightingmemory': 'Fighting Memory',
  'fightiniumz': 'Fightinium Z',
  'figyberry': 'Figy Berry',
  'firegem': 'Fire Gem',
  'firememory': 'Fire Memory',
  'firestone': 'Fire Stone',
  'firiumz': 'Firium Z',
  'fistplate': 'Fist Plate',
  'flameorb': 'Flame Orb',
  'flameplate': 'Flame Plate',
  'floatstone': 'Float Stone',
  'flyinggem': 'Flying Gem',
  'flyingmemory': 'Flying Memory',
  'flyiniumz': 'Flyinium Z',
  'focusband': 'Focus Band',
  'focussash': 'Focus Sash',
  'friendball': 'Friend Ball',
  'fullincense': 'Full Incense',
  'galladite': 'Galladite',
  'ganlonberry': 'Ganlon Berry',
  'garchompite': 'Garchompite',
  'gardevoirite': 'Gardevoirite',
  'gengarite': 'Gengarite',
  'ghostgem': 'Ghost Gem',
  'ghostmemory': 'Ghost Memory',
  'ghostiumz': 'Ghostium Z',
  'glalitite': 'Glalitite',
  'grassgem': 'Grass Gem',
  'grassmemory': 'Grass Memory',
  'grassiumz': 'Grassium Z',
  'grassyseed': 'Grassy Seed',
  'greatball': 'Great Ball',
  'grepaberry': 'Grepa Berry',
  'gripclaw': 'Grip Claw',
  'griseousorb': 'Griseous Orb',
  'groundgem': 'Ground Gem',
  'groundmemory': 'Ground Memory',
  'groundiumz': 'Groundium Z',
  'gyaradosite': 'Gyaradosite',
  'habanberry': 'Haban Berry',
  'hardstone': 'Hard Stone',
  'healball': 'Heal Ball',
  'heatrock': 'Heat Rock',
  'heavyball': 'Heavy Ball',
  'helixfossil': 'Helix Fossil',
  'heracronite': 'Heracronite',
  'hondewberry': 'Hondew Berry',
  'houndoominite': 'Houndoominite',
  'iapapaberry': 'Iapapa Berry',
  'icegem': 'Ice Gem',
  'icememory': 'Ice Memory',
  'icestone': 'Ice Stone',
  'icicleplate': 'Icicle Plate',
  'iciumz': 'Icium Z',
  'icyrock': 'Icy Rock',
  'inciniumz': 'Incinium Z',
  'insectplate': 'Insect Plate',
  'ironball': 'Iron Ball',
  'ironplate': 'Iron Plate',
  'jabocaberry': 'Jaboca Berry',
  'jawfossil': 'Jaw Fossil',
  'kasibberry': 'Kasib Berry',
  'kebiaberry': 'Kebia Berry',
  'keeberry': 'Kee Berry',
  'kelpsyberry': 'Kelpsy Berry',
  'kangaskhanite': 'Kangaskhanite',
  'kingsrock': 'King\'s Rock',
  'kommoniumz': 'Kommonium Z',
  'laggingtail': 'Lagging Tail',
  'lansatberry': 'Lansat Berry',
  'latiasite': 'Latiasite',
  'latiosite': 'Latiosite',
  'laxincense': 'Lax Incense',
  'leafstone': 'Leaf Stone',
  'leftovers': 'Leftovers',
  'leppaberry': 'Leppa Berry',
  'levelball': 'Level Ball',
  'liechiberry': 'Liechi Berry',
  'lifeorb': 'Life Orb',
  'lightball': 'Light Ball',
  'lightclay': 'Light Clay',
  'lopunnite': 'Lopunnite',
  'loveball': 'Love Ball',
  'lucarionite': 'Lucarionite',
  'luckypunch': 'Lucky Punch',
  'lumberry': 'Lum Berry',
  'luminousmoss': 'Luminous Moss',
  'lunaliumz': 'Lunalium Z',
  'lureball': 'Lure Ball',
  'lustrousorb': 'Lustrous Orb',
  'luxuryball': 'Luxury Ball',
  'lycaniumz': 'Lycanium Z',
  'machobrace': 'Macho Brace',
  'magmarizer': 'Magmarizer',
  'magnet': 'Magnet',
  'magoberry': 'Mago Berry',
  'magostberry': 'Magost Berry',
  'mail': 'Mail',
  'manectite': 'Manectite',
  'marangaberry': 'Maranga Berry',
  'marshadiumz': 'Marshadium Z',
  'masterball': 'Master Ball',
  'mawilite': 'Mawilite',
  'meadowplate': 'Meadow Plate',
  'medichamite': 'Medichamite',
  'mentalherb': 'Mental Herb',
  'metagrossite': 'Metagrossite',
  'metalcoat': 'Metal Coat',
  'metalpowder': 'Metal Powder',
  'metronome': 'Metronome',
  'mewniumz': 'Mewnium Z',
  'mewtwonitex': 'Mewtwonite X',
  'mewtwonitey': 'Mewtwonite Y',
  'micleberry': 'Micle Berry',
  'mimikiumz': 'Mimikium Z',
  'mindplate': 'Mind Plate',
  'miracleseed': 'Miracle Seed',
  'mistyseed': 'Misty Seed',
  'moonball': 'Moon Ball',
  'moonstone': 'Moon Stone',
  'muscleband': 'Muscle Band',
  'mysticwater': 'Mystic Water',
  'nanabberry': 'Nanab Berry',
  'nestball': 'Nest Ball',
  'netball': 'Net Ball',
  'nevermeltice': 'Never-Melt Ice',
  'nomelberry': 'Nomel Berry',
  'normalgem': 'Normal Gem',
  'normaliumz': 'Normalium Z',
  'occaberry': 'Occa Berry',
  'oddincense': 'Odd Incense',
  'oldamber': 'Old Amber',
  'oranberry': 'Oran Berry',
  'ovalstone': 'Oval Stone',
  'pamtreberry': 'Pamtre Berry',
  'parkball': 'Park Ball',
  'passhoberry': 'Passho Berry',
  'payapaberry': 'Payapa Berry',
  'pechaberry': 'Pecha Berry',
  'persimberry': 'Persim Berry',
  'petayaberry': 'Petaya Berry',
  'pidgeotite': 'Pidgeotite',
  'pikaniumz': 'Pikanium Z',
  'pikashuniumz': 'Pikashunium Z',
  'pinapberry': 'Pinap Berry',
  'pinsirite': 'Pinsirite',
  'pixieplate': 'Pixie Plate',
  'plumefossil': 'Plume Fossil',
  'poisonbarb': 'Poison Barb',
  'poisongem': 'Poison Gem',
  'poisonmemory': 'Poison Memory',
  'poisoniumz': 'Poisonium Z',
  'pokeball': 'Poke Ball',
  'pomegberry': 'Pomeg Berry',
  'poweranklet': 'Power Anklet',
  'powerband': 'Power Band',
  'powerbelt': 'Power Belt',
  'powerbracer': 'Power Bracer',
  'powerherb': 'Power Herb',
  'powerlens': 'Power Lens',
  'powerweight': 'Power Weight',
  'premierball': 'Premier Ball',
  'primariumz': 'Primarium Z',
  'prismscale': 'Prism Scale',
  'protectivepads': 'Protective Pads',
  'protector': 'Protector',
  'psychicgem': 'Psychic Gem',
  'psychicmemory': 'Psychic Memory',
  'psychicseed': 'Psychic Seed',
  'psychiumz': 'Psychium Z',
  'qualotberry': 'Qualot Berry',
  'quickball': 'Quick Ball',
  'quickclaw': 'Quick Claw',
  'quickpowder': 'Quick Powder',
  'rabutaberry': 'Rabuta Berry',
  'rarebone': 'Rare Bone',
  'rawstberry': 'Rawst Berry',
  'razorclaw': 'Razor Claw',
  'razorfang': 'Razor Fang',
  'razzberry': 'Razz Berry',
  'reapercloth': 'Reaper Cloth',
  'redcard': 'Red Card',
  'redorb': 'Red Orb',
  'repeatball': 'Repeat Ball',
  'rindoberry': 'Rindo Berry',
  'ringtarget': 'Ring Target',
  'rockgem': 'Rock Gem',
  'rockincense': 'Rock Incense',
  'rockmemory': 'Rock Memory',
  'rockiumz': 'Rockium Z',
  'rockyhelmet': 'Rocky Helmet',
  'rootfossil': 'Root Fossil',
  'roseincense': 'Rose Incense',
  'roseliberry': 'Roseli Berry',
  'rowapberry': 'Rowap Berry',
  'sablenite': 'Sablenite',
  'sachet': 'Sachet',
  'safariball': 'Safari Ball',
  'safetygoggles': 'Safety Goggles',
  'sailfossil': 'Sail Fossil',
  'salacberry': 'Salac Berry',
  'salamencite': 'Salamencite',
  'sceptilite': 'Sceptilite',
  'scizorite': 'Scizorite',
  'scopelens': 'Scope Lens',
  'seaincense': 'Sea Incense',
  'sharpbeak': 'Sharp Beak',
  'sharpedonite': 'Sharpedonite',
  'shedshell': 'Shed Shell',
  'shellbell': 'Shell Bell',
  'shinystone': 'Shiny Stone',
  'shockdrive': 'Shock Drive',
  'shucaberry': 'Shuca Berry',
  'silkscarf': 'Silk Scarf',
  'silverpowder': 'SilverPowder',
  'sitrusberry': 'Sitrus Berry',
  'skullfossil': 'Skull Fossil',
  'skyplate': 'Sky Plate',
  'slowbronite': 'Slowbronite',
  'smoothrock': 'Smooth Rock',
  'snorliumz': 'Snorlium Z',
  'snowball': 'Snowball',
  'softsand': 'Soft Sand',
  'solganiumz': 'Solganium Z',
  'souldew': 'Soul Dew',
  'spelltag': 'Spell Tag',
  'spelonberry': 'Spelon Berry',
  'splashplate': 'Splash Plate',
  'spookyplate': 'Spooky Plate',
  'sportball': 'Sport Ball',
  'starfberry': 'Starf Berry',
  'steelixite': 'Steelixite',
  'steelgem': 'Steel Gem',
  'steelmemory': 'Steel Memory',
  'steeliumz': 'Steelium Z',
  'stick': 'Stick',
  'stickybarb': 'Sticky Barb',
  'stoneplate': 'Stone Plate',
  'sunstone': 'Sun Stone',
  'swampertite': 'Swampertite',
  'tamatoberry': 'Tamato Berry',
  'tangaberry': 'Tanga Berry',
  'tapuniumz': 'Tapunium Z',
  'terrainextender': 'Terrain Extender',
  'thickclub': 'Thick Club',
  'thunderstone': 'Thunder Stone',
  'timerball': 'Timer Ball',
  'toxicorb': 'Toxic Orb',
  'toxicplate': 'Toxic Plate',
  'twistedspoon': 'Twisted Spoon',
  'tyranitarite': 'Tyranitarite',
  'ultraball': 'Ultra Ball',
  'ultranecroziumz': 'Ultranecrozium Z',
  'upgrade': 'Up-Grade',
  'venusaurite': 'Venusaurite',
  'wacanberry': 'Wacan Berry',
  'watergem': 'Water Gem',
  'watermemory': 'Water Memory',
  'waterstone': 'Water Stone',
  'wateriumz': 'Waterium Z',
  'watmelberry': 'Watmel Berry',
  'waveincense': 'Wave Incense',
  'weaknesspolicy': 'Weakness Policy',
  'wepearberry': 'Wepear Berry',
  'whippeddream': 'Whipped Dream',
  'whiteherb': 'White Herb',
  'widelens': 'Wide Lens',
  'wikiberry': 'Wiki Berry',
  'wiseglasses': 'Wise Glasses',
  'yacheberry': 'Yache Berry',
  'zapplate': 'Zap Plate',
  'zoomlens': 'Zoom Lens',
  'berserkgene': 'Berserk Gene',
  'berry': 'Berry',
  'bitterberry': 'Bitter Berry',
  'burntberry': 'Burnt Berry',
  'goldberry': 'Gold Berry',
  'iceberry': 'Ice Berry',
  'mintberry': 'Mint Berry',
  'miracleberry': 'Miracle Berry',
  'mysteryberry': 'Mystery Berry',
  'pinkbow': 'Pink Bow',
  'polkadotbow': 'Polkadot Bow',
  'przcureberry': 'PRZ Cure Berry',
  'psncureberry': 'PSN Cure Berry',
  'crucibellite': 'Crucibellite'
};

const MOVES = {
  '10000000voltthunderbolt': '10,000,000 Volt Thunderbolt',
  'absorb': 'Absorb',
  'accelerock': 'Accelerock',
  'acid': 'Acid',
  'acidarmor': 'Acid Armor',
  'aciddownpour': 'Acid Downpour',
  'acidspray': 'Acid Spray',
  'acrobatics': 'Acrobatics',
  'acupressure': 'Acupressure',
  'aerialace': 'Aerial Ace',
  'aeroblast': 'Aeroblast',
  'afteryou': 'After You',
  'agility': 'Agility',
  'aircutter': 'Air Cutter',
  'airslash': 'Air Slash',
  'alloutpummeling': 'All-Out Pummeling',
  'allyswitch': 'Ally Switch',
  'amnesia': 'Amnesia',
  'anchorshot': 'Anchor Shot',
  'ancientpower': 'Ancient Power',
  'aquajet': 'Aqua Jet',
  'aquaring': 'Aqua Ring',
  'aquatail': 'Aqua Tail',
  'armthrust': 'Arm Thrust',
  'aromatherapy': 'Aromatherapy',
  'aromaticmist': 'Aromatic Mist',
  'assist': 'Assist',
  'assurance': 'Assurance',
  'astonish': 'Astonish',
  'attackorder': 'Attack Order',
  'attract': 'Attract',
  'aurasphere': 'Aura Sphere',
  'aurorabeam': 'Aurora Beam',
  'auroraveil': 'Aurora Veil',
  'autotomize': 'Autotomize',
  'avalanche': 'Avalanche',
  'babydolleyes': 'Baby-Doll Eyes',
  'baddybad': 'Baddy Bad',
  'banefulbunker': 'Baneful Bunker',
  'barrage': 'Barrage',
  'barrier': 'Barrier',
  'batonpass': 'Baton Pass',
  'beakblast': 'Beak Blast',
  'beatup': 'Beat Up',
  'belch': 'Belch',
  'bellydrum': 'Belly Drum',
  'bestow': 'Bestow',
  'bide': 'Bide',
  'bind': 'Bind',
  'bite': 'Bite',
  'blackholeeclipse': 'Black Hole Eclipse',
  'blastburn': 'Blast Burn',
  'blazekick': 'Blaze Kick',
  'blizzard': 'Blizzard',
  'block': 'Block',
  'bloomdoom': 'Bloom Doom',
  'blueflare': 'Blue Flare',
  'bodyslam': 'Body Slam',
  'boltstrike': 'Bolt Strike',
  'boneclub': 'Bone Club',
  'bonerush': 'Bone Rush',
  'bonemerang': 'Bonemerang',
  'boomburst': 'Boomburst',
  'bounce': 'Bounce',
  'bouncybubble': 'Bouncy Bubble',
  'bravebird': 'Brave Bird',
  'breakneckblitz': 'Breakneck Blitz',
  'brickbreak': 'Brick Break',
  'brine': 'Brine',
  'brutalswing': 'Brutal Swing',
  'bubble': 'Bubble',
  'bubblebeam': 'Bubble Beam',
  'bugbite': 'Bug Bite',
  'bugbuzz': 'Bug Buzz',
  'bulkup': 'Bulk Up',
  'bulldoze': 'Bulldoze',
  'bulletpunch': 'Bullet Punch',
  'bulletseed': 'Bullet Seed',
  'burnup': 'Burn Up',
  'buzzybuzz': 'Buzzy Buzz',
  'calmmind': 'Calm Mind',
  'camouflage': 'Camouflage',
  'captivate': 'Captivate',
  'catastropika': 'Catastropika',
  'celebrate': 'Celebrate',
  'charge': 'Charge',
  'chargebeam': 'Charge Beam',
  'charm': 'Charm',
  'chatter': 'Chatter',
  'chipaway': 'Chip Away',
  'circlethrow': 'Circle Throw',
  'clamp': 'Clamp',
  'clangingscales': 'Clanging Scales',
  'clangoroussoulblaze': 'Clangorous Soulblaze',
  'clearsmog': 'Clear Smog',
  'closecombat': 'Close Combat',
  'coil': 'Coil',
  'cometpunch': 'Comet Punch',
  'confide': 'Confide',
  'confuseray': 'Confuse Ray',
  'confusion': 'Confusion',
  'constrict': 'Constrict',
  'continentalcrush': 'Continental Crush',
  'conversion': 'Conversion',
  'conversion2': 'Conversion 2',
  'copycat': 'Copycat',
  'coreenforcer': 'Core Enforcer',
  'corkscrewcrash': 'Corkscrew Crash',
  'cosmicpower': 'Cosmic Power',
  'cottonguard': 'Cotton Guard',
  'cottonspore': 'Cotton Spore',
  'counter': 'Counter',
  'covet': 'Covet',
  'crabhammer': 'Crabhammer',
  'craftyshield': 'Crafty Shield',
  'crosschop': 'Cross Chop',
  'crosspoison': 'Cross Poison',
  'crunch': 'Crunch',
  'crushclaw': 'Crush Claw',
  'crushgrip': 'Crush Grip',
  'curse': 'Curse',
  'cut': 'Cut',
  'darkpulse': 'Dark Pulse',
  'darkvoid': 'Dark Void',
  'darkestlariat': 'Darkest Lariat',
  'dazzlinggleam': 'Dazzling Gleam',
  'defendorder': 'Defend Order',
  'defensecurl': 'Defense Curl',
  'defog': 'Defog',
  'destinybond': 'Destiny Bond',
  'detect': 'Detect',
  'devastatingdrake': 'Devastating Drake',
  'diamondstorm': 'Diamond Storm',
  'dig': 'Dig',
  'disable': 'Disable',
  'disarmingvoice': 'Disarming Voice',
  'discharge': 'Discharge',
  'dive': 'Dive',
  'dizzypunch': 'Dizzy Punch',
  'doomdesire': 'Doom Desire',
  'doubleedge': 'Double-Edge',
  'doublehit': 'Double Hit',
  'doubleironbash': 'Double Iron Bash',
  'doublekick': 'Double Kick',
  'doubleslap': 'Double Slap',
  'doubleteam': 'Double Team',
  'dracometeor': 'Draco Meteor',
  'dragonascent': 'Dragon Ascent',
  'dragonbreath': 'Dragon Breath',
  'dragonclaw': 'Dragon Claw',
  'dragondance': 'Dragon Dance',
  'dragonhammer': 'Dragon Hammer',
  'dragonpulse': 'Dragon Pulse',
  'dragonrage': 'Dragon Rage',
  'dragonrush': 'Dragon Rush',
  'dragontail': 'Dragon Tail',
  'drainingkiss': 'Draining Kiss',
  'drainpunch': 'Drain Punch',
  'dreameater': 'Dream Eater',
  'drillpeck': 'Drill Peck',
  'drillrun': 'Drill Run',
  'dualchop': 'Dual Chop',
  'dynamicpunch': 'Dynamic Punch',
  'earthpower': 'Earth Power',
  'earthquake': 'Earthquake',
  'echoedvoice': 'Echoed Voice',
  'eerieimpulse': 'Eerie Impulse',
  'eggbomb': 'Egg Bomb',
  'electricterrain': 'Electric Terrain',
  'electrify': 'Electrify',
  'electroball': 'Electro Ball',
  'electroweb': 'Electroweb',
  'embargo': 'Embargo',
  'ember': 'Ember',
  'encore': 'Encore',
  'endeavor': 'Endeavor',
  'endure': 'Endure',
  'energyball': 'Energy Ball',
  'entrainment': 'Entrainment',
  'eruption': 'Eruption',
  'explosion': 'Explosion',
  'extrasensory': 'Extrasensory',
  'extremeevoboost': 'Extreme Evoboost',
  'extremespeed': 'Extreme Speed',
  'facade': 'Facade',
  'feintattack': 'Feint Attack',
  'fairylock': 'Fairy Lock',
  'fairywind': 'Fairy Wind',
  'fakeout': 'Fake Out',
  'faketears': 'Fake Tears',
  'falseswipe': 'False Swipe',
  'featherdance': 'Feather Dance',
  'feint': 'Feint',
  'fellstinger': 'Fell Stinger',
  'fierydance': 'Fiery Dance',
  'finalgambit': 'Final Gambit',
  'fireblast': 'Fire Blast',
  'firefang': 'Fire Fang',
  'firelash': 'Fire Lash',
  'firepledge': 'Fire Pledge',
  'firepunch': 'Fire Punch',
  'firespin': 'Fire Spin',
  'firstimpression': 'First Impression',
  'fissure': 'Fissure',
  'flail': 'Flail',
  'flameburst': 'Flame Burst',
  'flamecharge': 'Flame Charge',
  'flamewheel': 'Flame Wheel',
  'flamethrower': 'Flamethrower',
  'flareblitz': 'Flare Blitz',
  'flash': 'Flash',
  'flashcannon': 'Flash Cannon',
  'flatter': 'Flatter',
  'fleurcannon': 'Fleur Cannon',
  'fling': 'Fling',
  'floatyfall': 'Floaty Fall',
  'floralhealing': 'Floral Healing',
  'flowershield': 'Flower Shield',
  'fly': 'Fly',
  'flyingpress': 'Flying Press',
  'focusblast': 'Focus Blast',
  'focusenergy': 'Focus Energy',
  'focuspunch': 'Focus Punch',
  'followme': 'Follow Me',
  'forcepalm': 'Force Palm',
  'foresight': 'Foresight',
  'forestscurse': 'Forest\'s Curse',
  'foulplay': 'Foul Play',
  'freezedry': 'Freeze-Dry',
  'freezeshock': 'Freeze Shock',
  'freezyfrost': 'Freezy Frost',
  'frenzyplant': 'Frenzy Plant',
  'frostbreath': 'Frost Breath',
  'frustration': 'Frustration',
  'furyattack': 'Fury Attack',
  'furycutter': 'Fury Cutter',
  'furyswipes': 'Fury Swipes',
  'fusionbolt': 'Fusion Bolt',
  'fusionflare': 'Fusion Flare',
  'futuresight': 'Future Sight',
  'gastroacid': 'Gastro Acid',
  'geargrind': 'Gear Grind',
  'gearup': 'Gear Up',
  'genesissupernova': 'Genesis Supernova',
  'geomancy': 'Geomancy',
  'gigadrain': 'Giga Drain',
  'gigaimpact': 'Giga Impact',
  'gigavolthavoc': 'Gigavolt Havoc',
  'glaciate': 'Glaciate',
  'glare': 'Glare',
  'glitzyglow': 'Glitzy Glow',
  'grassknot': 'Grass Knot',
  'grasspledge': 'Grass Pledge',
  'grasswhistle': 'Grass Whistle',
  'grassyterrain': 'Grassy Terrain',
  'gravity': 'Gravity',
  'growl': 'Growl',
  'growth': 'Growth',
  'grudge': 'Grudge',
  'guardsplit': 'Guard Split',
  'guardswap': 'Guard Swap',
  'guardianofalola': 'Guardian of Alola',
  'guillotine': 'Guillotine',
  'gunkshot': 'Gunk Shot',
  'gust': 'Gust',
  'gyroball': 'Gyro Ball',
  'hail': 'Hail',
  'hammerarm': 'Hammer Arm',
  'happyhour': 'Happy Hour',
  'harden': 'Harden',
  'haze': 'Haze',
  'headcharge': 'Head Charge',
  'headsmash': 'Head Smash',
  'headbutt': 'Headbutt',
  'healbell': 'Heal Bell',
  'healblock': 'Heal Block',
  'healorder': 'Heal Order',
  'healpulse': 'Heal Pulse',
  'healingwish': 'Healing Wish',
  'heartstamp': 'Heart Stamp',
  'heartswap': 'Heart Swap',
  'heatcrash': 'Heat Crash',
  'heatwave': 'Heat Wave',
  'heavyslam': 'Heavy Slam',
  'helpinghand': 'Helping Hand',
  'hex': 'Hex',
  'hiddenpower': 'Hidden Power',
  'hiddenpowerbug': 'Hidden Power Bug',
  'hiddenpowerdark': 'Hidden Power Dark',
  'hiddenpowerdragon': 'Hidden Power Dragon',
  'hiddenpowerelectric': 'Hidden Power Electric',
  'hiddenpowerfighting': 'Hidden Power Fighting',
  'hiddenpowerfire': 'Hidden Power Fire',
  'hiddenpowerflying': 'Hidden Power Flying',
  'hiddenpowerghost': 'Hidden Power Ghost',
  'hiddenpowergrass': 'Hidden Power Grass',
  'hiddenpowerground': 'Hidden Power Ground',
  'hiddenpowerice': 'Hidden Power Ice',
  'hiddenpowerpoison': 'Hidden Power Poison',
  'hiddenpowerpsychic': 'Hidden Power Psychic',
  'hiddenpowerrock': 'Hidden Power Rock',
  'hiddenpowersteel': 'Hidden Power Steel',
  'hiddenpowerwater': 'Hidden Power Water',
  'highhorsepower': 'High Horsepower',
  'highjumpkick': 'High Jump Kick',
  'holdback': 'Hold Back',
  'holdhands': 'Hold Hands',
  'honeclaws': 'Hone Claws',
  'hornattack': 'Horn Attack',
  'horndrill': 'Horn Drill',
  'hornleech': 'Horn Leech',
  'howl': 'Howl',
  'hurricane': 'Hurricane',
  'hydrocannon': 'Hydro Cannon',
  'hydropump': 'Hydro Pump',
  'hydrovortex': 'Hydro Vortex',
  'hyperbeam': 'Hyper Beam',
  'hyperfang': 'Hyper Fang',
  'hyperspacefury': 'Hyperspace Fury',
  'hyperspacehole': 'Hyperspace Hole',
  'hypervoice': 'Hyper Voice',
  'hypnosis': 'Hypnosis',
  'iceball': 'Ice Ball',
  'icebeam': 'Ice Beam',
  'iceburn': 'Ice Burn',
  'icefang': 'Ice Fang',
  'icehammer': 'Ice Hammer',
  'icepunch': 'Ice Punch',
  'iceshard': 'Ice Shard',
  'iciclecrash': 'Icicle Crash',
  'iciclespear': 'Icicle Spear',
  'icywind': 'Icy Wind',
  'imprison': 'Imprison',
  'incinerate': 'Incinerate',
  'inferno': 'Inferno',
  'infernooverdrive': 'Inferno Overdrive',
  'infestation': 'Infestation',
  'ingrain': 'Ingrain',
  'instruct': 'Instruct',
  'iondeluge': 'Ion Deluge',
  'irondefense': 'Iron Defense',
  'ironhead': 'Iron Head',
  'irontail': 'Iron Tail',
  'judgment': 'Judgment',
  'jumpkick': 'Jump Kick',
  'karatechop': 'Karate Chop',
  'kinesis': 'Kinesis',
  'kingsshield': 'King\'s Shield',
  'knockoff': 'Knock Off',
  'landswrath': 'Land\'s Wrath',
  'laserfocus': 'Laser Focus',
  'lastresort': 'Last Resort',
  'lavaplume': 'Lava Plume',
  'leafblade': 'Leaf Blade',
  'leafstorm': 'Leaf Storm',
  'leaftornado': 'Leaf Tornado',
  'leafage': 'Leafage',
  'leechlife': 'Leech Life',
  'leechseed': 'Leech Seed',
  'leer': 'Leer',
  'letssnuggleforever': 'Let\'s Snuggle Forever',
  'lick': 'Lick',
  'lightofruin': 'Light of Ruin',
  'lightscreen': 'Light Screen',
  'lightthatburnsthesky': 'Light That Burns the Sky',
  'liquidation': 'Liquidation',
  'lockon': 'Lock-On',
  'lovelykiss': 'Lovely Kiss',
  'lowkick': 'Low Kick',
  'lowsweep': 'Low Sweep',
  'luckychant': 'Lucky Chant',
  'lunardance': 'Lunar Dance',
  'lunge': 'Lunge',
  'lusterpurge': 'Luster Purge',
  'machpunch': 'Mach Punch',
  'magiccoat': 'Magic Coat',
  'magicroom': 'Magic Room',
  'magicalleaf': 'Magical Leaf',
  'magmastorm': 'Magma Storm',
  'magnetbomb': 'Magnet Bomb',
  'magneticflux': 'Magnetic Flux',
  'magnetrise': 'Magnet Rise',
  'magnitude': 'Magnitude',
  'maliciousmoonsault': 'Malicious Moonsault',
  'matblock': 'Mat Block',
  'mefirst': 'Me First',
  'meanlook': 'Mean Look',
  'meditate': 'Meditate',
  'megadrain': 'Mega Drain',
  'megakick': 'Mega Kick',
  'megapunch': 'Mega Punch',
  'megahorn': 'Megahorn',
  'memento': 'Memento',
  'menacingmoonrazemaelstrom': 'Menacing Moonraze Maelstrom',
  'metalburst': 'Metal Burst',
  'metalclaw': 'Metal Claw',
  'metalsound': 'Metal Sound',
  'meteormash': 'Meteor Mash',
  'metronome': 'Metronome',
  'milkdrink': 'Milk Drink',
  'mimic': 'Mimic',
  'mindblown': 'Mind Blown',
  'mindreader': 'Mind Reader',
  'minimize': 'Minimize',
  'miracleeye': 'Miracle Eye',
  'mirrorcoat': 'Mirror Coat',
  'mirrormove': 'Mirror Move',
  'mirrorshot': 'Mirror Shot',
  'mist': 'Mist',
  'mistball': 'Mist Ball',
  'mistyterrain': 'Misty Terrain',
  'moonblast': 'Moonblast',
  'moongeistbeam': 'Moongeist Beam',
  'moonlight': 'Moonlight',
  'morningsun': 'Morning Sun',
  'mudslap': 'Mud-Slap',
  'mudbomb': 'Mud Bomb',
  'mudshot': 'Mud Shot',
  'mudsport': 'Mud Sport',
  'muddywater': 'Muddy Water',
  'multiattack': 'Multi-Attack',
  'mysticalfire': 'Mystical Fire',
  'nastyplot': 'Nasty Plot',
  'naturalgift': 'Natural Gift',
  'naturepower': 'Nature Power',
  'naturesmadness': 'Nature\'s Madness',
  'needlearm': 'Needle Arm',
  'neverendingnightmare': 'Never-Ending Nightmare',
  'nightdaze': 'Night Daze',
  'nightshade': 'Night Shade',
  'nightslash': 'Night Slash',
  'nightmare': 'Nightmare',
  'nobleroar': 'Noble Roar',
  'nuzzle': 'Nuzzle',
  'oblivionwing': 'Oblivion Wing',
  'oceanicoperetta': 'Oceanic Operetta',
  'octazooka': 'Octazooka',
  'odorsleuth': 'Odor Sleuth',
  'ominouswind': 'Ominous Wind',
  'originpulse': 'Origin Pulse',
  'outrage': 'Outrage',
  'overheat': 'Overheat',
  'painsplit': 'Pain Split',
  'paraboliccharge': 'Parabolic Charge',
  'partingshot': 'Parting Shot',
  'payday': 'Pay Day',
  'payback': 'Payback',
  'peck': 'Peck',
  'perishsong': 'Perish Song',
  'petalblizzard': 'Petal Blizzard',
  'petaldance': 'Petal Dance',
  'phantomforce': 'Phantom Force',
  'photongeyser': 'Photon Geyser',
  'pikapapow': 'Pika Papow',
  'pinmissile': 'Pin Missile',
  'plasmafists': 'Plasma Fists',
  'playnice': 'Play Nice',
  'playrough': 'Play Rough',
  'pluck': 'Pluck',
  'poisonfang': 'Poison Fang',
  'poisongas': 'Poison Gas',
  'poisonjab': 'Poison Jab',
  'poisonpowder': 'Poison Powder',
  'poisonsting': 'Poison Sting',
  'poisontail': 'Poison Tail',
  'pollenpuff': 'Pollen Puff',
  'pound': 'Pound',
  'powder': 'Powder',
  'powdersnow': 'Powder Snow',
  'powergem': 'Power Gem',
  'powersplit': 'Power Split',
  'powerswap': 'Power Swap',
  'powertrick': 'Power Trick',
  'powertrip': 'Power Trip',
  'poweruppunch': 'Power-Up Punch',
  'powerwhip': 'Power Whip',
  'precipiceblades': 'Precipice Blades',
  'present': 'Present',
  'prismaticlaser': 'Prismatic Laser',
  'protect': 'Protect',
  'psybeam': 'Psybeam',
  'psychup': 'Psych Up',
  'psychic': 'Psychic',
  'psychicfangs': 'Psychic Fangs',
  'psychicterrain': 'Psychic Terrain',
  'psychoboost': 'Psycho Boost',
  'psychocut': 'Psycho Cut',
  'psychoshift': 'Psycho Shift',
  'psyshock': 'Psyshock',
  'psystrike': 'Psystrike',
  'psywave': 'Psywave',
  'pulverizingpancake': 'Pulverizing Pancake',
  'punishment': 'Punishment',
  'purify': 'Purify',
  'pursuit': 'Pursuit',
  'quash': 'Quash',
  'quickattack': 'Quick Attack',
  'quickguard': 'Quick Guard',
  'quiverdance': 'Quiver Dance',
  'rage': 'Rage',
  'ragepowder': 'Rage Powder',
  'raindance': 'Rain Dance',
  'rapidspin': 'Rapid Spin',
  'razorleaf': 'Razor Leaf',
  'razorshell': 'Razor Shell',
  'razorwind': 'Razor Wind',
  'recover': 'Recover',
  'recycle': 'Recycle',
  'reflect': 'Reflect',
  'reflecttype': 'Reflect Type',
  'refresh': 'Refresh',
  'relicsong': 'Relic Song',
  'rest': 'Rest',
  'retaliate': 'Retaliate',
  'return': 'Return',
  'revelationdance': 'Revelation Dance',
  'revenge': 'Revenge',
  'reversal': 'Reversal',
  'roar': 'Roar',
  'roaroftime': 'Roar of Time',
  'rockblast': 'Rock Blast',
  'rockclimb': 'Rock Climb',
  'rockpolish': 'Rock Polish',
  'rockslide': 'Rock Slide',
  'rocksmash': 'Rock Smash',
  'rockthrow': 'Rock Throw',
  'rocktomb': 'Rock Tomb',
  'rockwrecker': 'Rock Wrecker',
  'roleplay': 'Role Play',
  'rollingkick': 'Rolling Kick',
  'rollout': 'Rollout',
  'roost': 'Roost',
  'rototiller': 'Rototiller',
  'round': 'Round',
  'sacredfire': 'Sacred Fire',
  'sacredsword': 'Sacred Sword',
  'safeguard': 'Safeguard',
  'sandattack': 'Sand Attack',
  'sandtomb': 'Sand Tomb',
  'sandstorm': 'Sandstorm',
  'sappyseed': 'Sappy Seed',
  'savagespinout': 'Savage Spin-Out',
  'scald': 'Scald',
  'scaryface': 'Scary Face',
  'scratch': 'Scratch',
  'screech': 'Screech',
  'searingshot': 'Searing Shot',
  'searingsunrazesmash': 'Searing Sunraze Smash',
  'secretpower': 'Secret Power',
  'secretsword': 'Secret Sword',
  'seedbomb': 'Seed Bomb',
  'seedflare': 'Seed Flare',
  'seismictoss': 'Seismic Toss',
  'selfdestruct': 'Self-Destruct',
  'shadowball': 'Shadow Ball',
  'shadowbone': 'Shadow Bone',
  'shadowclaw': 'Shadow Claw',
  'shadowforce': 'Shadow Force',
  'shadowpunch': 'Shadow Punch',
  'shadowsneak': 'Shadow Sneak',
  'sharpen': 'Sharpen',
  'shatteredpsyche': 'Shattered Psyche',
  'sheercold': 'Sheer Cold',
  'shellsmash': 'Shell Smash',
  'shelltrap': 'Shell Trap',
  'shiftgear': 'Shift Gear',
  'shockwave': 'Shock Wave',
  'shoreup': 'Shore Up',
  'signalbeam': 'Signal Beam',
  'silverwind': 'Silver Wind',
  'simplebeam': 'Simple Beam',
  'sing': 'Sing',
  'sinisterarrowraid': 'Sinister Arrow Raid',
  'sizzlyslide': 'Sizzly Slide',
  'sketch': 'Sketch',
  'skillswap': 'Skill Swap',
  'skullbash': 'Skull Bash',
  'skyattack': 'Sky Attack',
  'skydrop': 'Sky Drop',
  'skyuppercut': 'Sky Uppercut',
  'slackoff': 'Slack Off',
  'slam': 'Slam',
  'slash': 'Slash',
  'sleeppowder': 'Sleep Powder',
  'sleeptalk': 'Sleep Talk',
  'sludge': 'Sludge',
  'sludgebomb': 'Sludge Bomb',
  'sludgewave': 'Sludge Wave',
  'smackdown': 'Smack Down',
  'smartstrike': 'Smart Strike',
  'smellingsalts': 'Smelling Salts',
  'smog': 'Smog',
  'smokescreen': 'Smokescreen',
  'snarl': 'Snarl',
  'snatch': 'Snatch',
  'snore': 'Snore',
  'spectralthief': 'Spectral Thief',
  'speedswap': 'Speed Swap',
  'spikyshield': 'Spiky Shield',
  'spiritshackle': 'Spirit Shackle',
  'soak': 'Soak',
  'softboiled': 'Soft-Boiled',
  'solarbeam': 'Solar Beam',
  'solarblade': 'Solar Blade',
  'sonicboom': 'Sonic Boom',
  'soulstealing7starstrike': 'Soul-Stealing 7-Star Strike',
  'spacialrend': 'Spacial Rend',
  'spark': 'Spark',
  'sparklingaria': 'Sparkling Aria',
  'sparklyswirl': 'Sparkly Swirl',
  'spiderweb': 'Spider Web',
  'spikecannon': 'Spike Cannon',
  'spikes': 'Spikes',
  'spitup': 'Spit Up',
  'spite': 'Spite',
  'splash': 'Splash',
  'splinteredstormshards': 'Splintered Stormshards',
  'splishysplash': 'Splishy Splash',
  'spore': 'Spore',
  'spotlight': 'Spotlight',
  'stealthrock': 'Stealth Rock',
  'steameruption': 'Steam Eruption',
  'steelwing': 'Steel Wing',
  'stickyweb': 'Sticky Web',
  'stockpile': 'Stockpile',
  'stokedsparksurfer': 'Stoked Sparksurfer',
  'stomp': 'Stomp',
  'stompingtantrum': 'Stomping Tantrum',
  'stoneedge': 'Stone Edge',
  'storedpower': 'Stored Power',
  'stormthrow': 'Storm Throw',
  'steamroller': 'Steamroller',
  'strength': 'Strength',
  'strengthsap': 'Strength Sap',
  'stringshot': 'String Shot',
  'struggle': 'Struggle',
  'strugglebug': 'Struggle Bug',
  'stunspore': 'Stun Spore',
  'submission': 'Submission',
  'substitute': 'Substitute',
  'subzeroslammer': 'Subzero Slammer',
  'suckerpunch': 'Sucker Punch',
  'sunnyday': 'Sunny Day',
  'sunsteelstrike': 'Sunsteel Strike',
  'superfang': 'Super Fang',
  'superpower': 'Superpower',
  'supersonic': 'Supersonic',
  'supersonicskystrike': 'Supersonic Skystrike',
  'surf': 'Surf',
  'swagger': 'Swagger',
  'swallow': 'Swallow',
  'sweetkiss': 'Sweet Kiss',
  'sweetscent': 'Sweet Scent',
  'swift': 'Swift',
  'switcheroo': 'Switcheroo',
  'swordsdance': 'Swords Dance',
  'synchronoise': 'Synchronoise',
  'synthesis': 'Synthesis',
  'tackle': 'Tackle',
  'tailglow': 'Tail Glow',
  'tailslap': 'Tail Slap',
  'tailwhip': 'Tail Whip',
  'tailwind': 'Tailwind',
  'takedown': 'Take Down',
  'taunt': 'Taunt',
  'tearfullook': 'Tearful Look',
  'technoblast': 'Techno Blast',
  'tectonicrage': 'Tectonic Rage',
  'teeterdance': 'Teeter Dance',
  'telekinesis': 'Telekinesis',
  'teleport': 'Teleport',
  'thief': 'Thief',
  'thousandarrows': 'Thousand Arrows',
  'thousandwaves': 'Thousand Waves',
  'thrash': 'Thrash',
  'throatchop': 'Throat Chop',
  'thunder': 'Thunder',
  'thunderfang': 'Thunder Fang',
  'thunderpunch': 'Thunder Punch',
  'thundershock': 'Thunder Shock',
  'thunderwave': 'Thunder Wave',
  'thunderbolt': 'Thunderbolt',
  'tickle': 'Tickle',
  'topsyturvy': 'Topsy-Turvy',
  'torment': 'Torment',
  'toxic': 'Toxic',
  'toxicspikes': 'Toxic Spikes',
  'toxicthread': 'Toxic Thread',
  'transform': 'Transform',
  'triattack': 'Tri Attack',
  'trick': 'Trick',
  'trickortreat': 'Trick-or-Treat',
  'trickroom': 'Trick Room',
  'triplekick': 'Triple Kick',
  'tropkick': 'Trop Kick',
  'trumpcard': 'Trump Card',
  'twineedle': 'Twineedle',
  'twinkletackle': 'Twinkle Tackle',
  'twister': 'Twister',
  'uturn': 'U-turn',
  'uproar': 'Uproar',
  'vcreate': 'V-create',
  'vacuumwave': 'Vacuum Wave',
  'veeveevolley': 'Veevee Volley',
  'venomdrench': 'Venom Drench',
  'venoshock': 'Venoshock',
  'vicegrip': 'Vice Grip',
  'vinewhip': 'Vine Whip',
  'vitalthrow': 'Vital Throw',
  'voltswitch': 'Volt Switch',
  'volttackle': 'Volt Tackle',
  'wakeupslap': 'Wake-Up Slap',
  'watergun': 'Water Gun',
  'waterpledge': 'Water Pledge',
  'waterpulse': 'Water Pulse',
  'watersport': 'Water Sport',
  'waterspout': 'Water Spout',
  'waterfall': 'Waterfall',
  'watershuriken': 'Water Shuriken',
  'weatherball': 'Weather Ball',
  'whirlpool': 'Whirlpool',
  'whirlwind': 'Whirlwind',
  'wideguard': 'Wide Guard',
  'wildcharge': 'Wild Charge',
  'willowisp': 'Will-O-Wisp',
  'wingattack': 'Wing Attack',
  'wish': 'Wish',
  'withdraw': 'Withdraw',
  'wonderroom': 'Wonder Room',
  'woodhammer': 'Wood Hammer',
  'workup': 'Work Up',
  'worryseed': 'Worry Seed',
  'wrap': 'Wrap',
  'wringout': 'Wring Out',
  'xscissor': 'X-Scissor',
  'yawn': 'Yawn',
  'zapcannon': 'Zap Cannon',
  'zenheadbutt': 'Zen Headbutt',
  'zingzap': 'Zing Zap',
  'zippyzap': 'Zippy Zap',
  'paleowave': 'Paleo Wave',
  'shadowstrike': 'Shadow Strike',
};

const NATURES = {
  'Adamant': ['atk', 'spa'],
  'Bashful': [undefined, undefined],
  'Bold': ['def', 'atk'],
  'Brave': ['atk', 'spe'],
  'Calm': ['spd', 'atk'],
  'Careful': ['spd', 'spa'],
  'Docile': [undefined, undefined],
  'Gentle': ['spd', 'def'],
  'Hardy': [undefined, undefined],
  'Hasty': ['spe', 'def'],
  'Impish': ['def', 'spa'],
  'Jolly': ['spe', 'spa'],
  'Lax': ['def', 'spd'],
  'Lonely': ['atk', 'def'],
  'Mild': ['spa', 'def'],
  'Modest': ['spa', 'atk'],
  'Naive': ['spe', 'spd'],
  'Naughty': ['atk', 'spd'],
  'Quiet': ['spa', 'spe'],
  'Quirky': [undefined, undefined],
  'Rash': ['spa', 'spd'],
  'Relaxed': ['def', 'spe'],
  'Sassy': ['spd', 'spe'],
  'Serious': [undefined, undefined],
  'Timid': ['spe', 'atk']
};

function displayStat(stat) {
  switch (stat) {
    case 'hp':
      return 'HP';
    case 'atk':
      return 'Atk';
    case 'def':
      return 'Def';
    case 'spa':
      return 'SpA';
    case 'spd':
      return 'SpD';
    case 'spe':
      return 'Spe';
    case 'spc':
      return 'Spc';
    default:
      throw new Error('unknown stat ' + stat);
  }
}

exports.ABILITIES = ABILITIES;
exports.ITEMS = ITEMS;
exports.MOVES = MOVES;
exports.NATURES = NATURES;
exports.displayStat = displayStat;
